services:
  obfs4-bridge:
    image: ghcr.io/gigirassy/docker-obfs4-bridge:main-alpine # want to use debian? remove -alpine part
    networks:
      - obfs4_bridge_external_network
    environment:
      # Exit with an error message if OR_PORT is unset or empty.
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      # Exit with an error message if PT_PORT is unset or empty.
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      # Exit with an error message if EMAIL is unset or empty.
      - EMAIL=${EMAIL:?Env var EMAIL is not set.} # this doesnt have to be an email
      # Nickname with default value: "DockerObfs4Bridge"
      - NICKNAME=${NICKNAME:-DockerObfs4Bridge}
      - OBFS4_ENABLE_ADDITIONAL_VARIABLES=1
      - OBFS4V_BridgeDistribution=settings # enable this to allow your bridge to be distributed to tor users that need it
    env_file:
      - .env
    volumes:
      - data:/var/lib/tor
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped

volumes:
  data:
    name: tor-datadir-${OR_PORT}-${PT_PORT}

networks:
  obfs4_bridge_external_network:

