name: Docker

on:
  schedule:
    - cron: '25 11 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-x86:
    name: Build on x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push x86 Alpine
        id: x86-alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-alpine-amd64
          outputs: type=image,digest=true

      - name: Build & Push x86 Void
        id: x86-void
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.void
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-void-amd64
          outputs: type=image,digest=true

  build-arm:
    name: Build on ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ARM Alpine
        id: arm-alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-alpine-arm64
          outputs: type=image,digest=true

      - name: Build & Push ARM Void
        id: arm-void
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.void
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-void-arm64
          outputs: type=image,digest=true

  manifest:
    name: Create & Push Multi-Arch Manifests
    needs: [build-x86, build-arm]
    runs-on: ubuntu-latest

    steps:
      - name: Log in to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Alpine Manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:alpine \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-alpine-amd64@${{ needs.build-x86.outputs['x86-alpine.digest'] }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-alpine-arm64@${{ needs.build-arm.outputs['arm-alpine.digest'] }}
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:alpine

      - name: Create Void Manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:void \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-void-amd64@${{ needs.build-x86.outputs['x86-void.digest'] }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-void-arm64@${{ needs.build-arm.outputs['arm-void.digest'] }}
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:void

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.0.0
        with:
          cosign-release: 'v2.2.4'

      - name: Sign Alpine Manifest
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:alpine

      - name: Sign Void Manifest
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:void
