name: Docker

on:
  schedule:
    - cron: '25 11 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-amd64:
    runs-on: depot-ubuntu-24.04-32
    outputs:
      amd_digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Build amd64 image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:alpine-amd64
          outputs: type=image,digest=true

  build-arm64:
    runs-on: depot-ubuntu-24.04-arm-32
    needs: build-amd64
    outputs:
      arm_digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Build arm64 image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:alpine-arm64
          outputs: type=image,digest=true

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multi-arch
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:alpine \
            ghcr.io/${{ github.repository }}:alpine-amd64@${{ needs.build-amd64.outputs.amd_digest }} \
            ghcr.io/${{ github.repository }}:alpine-arm64@${{ needs.build-arm64.outputs.arm_digest }}
