name: Docker

on:
  schedule:
    - cron: '25 11 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
    
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v8
        
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Build & push (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE }}:alpine-amd64
          outputs: type=image,digest=true

  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    needs: build-amd64
    steps:
      
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v8
        
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Build & push (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE }}:alpine-arm64
          outputs: type=image,digest=true

  manifest:
    name: Create multi-arch manifest
    needs: [ build-amd64, build-arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multi-arch tag
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools create \
            ${{ env.IMAGE }}:alpine \
            ${{ env.IMAGE }}:alpine-amd64 \
            ${{ env.IMAGE }}:alpine-arm64
